config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :member, lambda { |u| u.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :communities, path: '', except: :index do
    get 'admin/dashboard'

    namespace :admin do
      resource :community, only: [:edit, :update]
      resources :networks
      resources :events, except: [:show]
      resources :companies
      resources :members do
        patch 'resend_invitation', on: :member
      end
      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end

    resources :networks, path: '', only: :show do
      namespace :admin do
        resources :events, except: [:show]
        resources :companies
        resources :members do
          patch 'resend_invitation', on: :member
        end
      end

      resource :calendar, only: :show do
        get 'feeds/:auth_token/:type',
          to: 'calendar_feeds#subscribe',
          as: 'feeds',
          constraints: { type: /events|availabilities/ }
        get 'feeds/:auth_token/reservations',
          to: 'calendar_feeds#reservations',
          as: 'reservation_feeds'
      end

      get 'availabilities/:year/:month/:day',
          to: 'availabilities#calendar',
          as: 'availability_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      get 'events/:year/:month/:day',
          to: 'events#calendar',
          as: 'event_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      resources :messages, only: :index do
        get 'search', on: :collection
      end

      resources :members, only: [:index, :show] do
        member do
          patch :follow
          delete :unfollow
        end

        resources :activities, only: :index
        resource :calendar, only: :show
        resources :messages
        resources :discussions, only: :index

        get 'availabilities/:year/:month/:day',
            to: 'availabilities#slots',
            as: 'availability_slots',
            constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

        resources :availabilities, except: [:show] do
          resource :slots,
                   path: 'slots/:hour/:minute',
                   constraints: { hour: /\d{1,2}/, minute: /\d{1,2}/ } do
                     collection do
                       post :reserve, to: 'slots#create'
                       delete :release, to: 'slots#destroy'
                     end
                   end
        end
      end

      get 'discussions/tagged/:tag_id',
          to: 'discussions#index',
          as: 'discussion_tag'

      resources :discussions do
        resources :comments, only: [:create, :update, :destroy]
        member do
          patch :follow
          delete :unfollow
        end
      end

      resources :events, only: [:show] do
        member do
          patch :rsvp
        end
      end

      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end
  end

  scope ':community_id' do
    devise_for(
      :members,
      skip: [:registrations],
      controllers: {
        invitations: 'invitations',
        sessions: 'sessions'
      })
    as :member do
      delete '/leave', to: 'registrations#destroy', as: 'destroy_member_registration'
    end
    scope ':network_id' do
      as :member do
        scope 'account' do
          # settings & cancellation
          get '/', to: 'registrations#edit', as: 'edit_member_registration'
          put '/', to: 'registrations#update'
        end
      end
    end
  end

  root 'welcome#index'
  get 's3_callback/:model', to: 'uploads#s3_callback', as: "s3_callback"
  get '*missing' => redirect('/')
end

app/models/event.rb
class Event < ActiveRecord::Base
  LOCATION_TYPES = {
    address: 'Address',
    skype: 'Name',
    phone: 'Number',
    other: 'Info'
  }.freeze

  # Behaviors
  include TimeInZone
  include NetworksConcern
  time_in_zone_for :starts_at, :ends_at

  # Associations
  belongs_to :creator, class_name: 'Member'
  belongs_to :network

  has_many :rsvps, dependent: :destroy
  has_many :members, through: :rsvps do
    def attending
      where(rsvps: { state: 'attending' })
    end

    def maybe_attending
      where(rsvps: { state: 'maybe_attending' })
    end

    def not_attending
      where(rsvps: { state: 'not_attending' })
    end
  end

  has_many :activities,
           as: :resource,
           dependent: :destroy

  has_and_belongs_to_many :networks

  # Validations
  validates :location_detail,
            :starts_at,
            :ends_at,
            :title,
            :time_zone,
            :creator,
            presence: true
  validates :location_type, inclusion: { in: LOCATION_TYPES.keys.map(&:to_s) }
  validates :networks, presence: true
  validate :ends_at_cannot_precede_starts_at,
           if: -> { ends_at.present? && starts_at.present? }

  # Scopes
  scope :upcoming, -> { where('ends_at > ?', Time.zone.now) }
  scope :past, -> { where('ends_at < ?', Time.zone.now) }
  scope :ordered, -> { order(starts_at: :asc) }
  scope :on_date, ->(date, time_zone) do
    where(
      'date(starts_at::TIMESTAMPTZ AT TIME ZONE :time_zone) = :date',
      time_zone: ActiveSupport::TimeZone::MAPPING[time_zone],
      date: date
    )
  end

  before_validation :override_timezone
  after_create :create_activity

  def to_param
    "#{ id }-#{ title.parameterize }"
  end

  def location_coordinates
    "#{ location_latitude },#{ location_longitude }"
  end

  def at_address?
    location_type == 'address'
  end

  def ended?
    ends_at < Time.zone.now
  end

  def community
    networks.first.community
  end

  def to_ics(params = {})
    summary = "#{title}#{' (External)' if external}"
    tz = ActiveSupport::TimeZone::MAPPING[time_zone]

    event = Icalendar::Event.new
    event.dtstart = Icalendar::Values::DateTime.new(starts_at, tzid: tz)
    event.dtend = Icalendar::Values::DateTime.new(ends_at, tzid: tz)
    event.summary = "#{params[:state].humanize+' ' if params[:reserved]}#{summary}"
    event.description = "#{location_type}: #{location_detail}"
    event.organizer = "mailto:#{creator.email}"
    event.created = created_at
    event.last_modified = updated_at
    event.uid = SecureRandom.uuid
    event
  end

  private

  def create_activity
    networks.each do |network|
      Activity::EventCreating.create(owner: creator, event: self, network: network)
    end
  end

  def ends_at_cannot_precede_starts_at
    return if ends_at > starts_at
    errors.add(:ends_at, :cannot_precede_starts_at)
  end

  def override_timezone
    # TODO These conditions is temporary added to pass rspec Shoulda-matcher's method
    # `validate_presence_of` since it drops the attributes and breaks this callback
    if time_zone && starts_at && ends_at
      %w(starts_at ends_at).each do |attr|
        datetime = ActiveSupport::TimeZone.new(time_zone)
                                          .parse(attributes[attr].strftime('%F %T'))
        self.send(:"#{attr}=", datetime)
      end
    end
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < AdminController
    load_and_authorize_resource through: :current_community, except: [:new, :create]

    def create
      @event = Event.new(event_params)
      if @event.save
        redirect_to_admin_events_path('Event was successfully created.')
      else
        render 'new', alert: 'Error creating event.'
      end
    end

    def new
      @event = Event.new
      @event.assign_attributes(time_zone: current_member.time_zone)
    end

    def index
      @events = current_network.events if current_network
      @upcoming_events = @events.upcoming.ordered.page params[:page]
      @past_events     = @events.past.ordered
    end

    def update
      if @event.update(event_params)
        redirect_to_admin_events_path('Event was successfully updated.')
      else
        render 'edit', alert: 'Error updating event.'
      end
    end

    def edit
    end

    def destroy
      @event.destroy
      redirect_to_admin_events_path('Event was successfully deleted.')
    end

    private

    def redirect_to_admin_events_path(notice)
      redirect_to(
        community_admin_events_path(current_community), notice: notice)
    end

    def event_params
      params.require(:event).permit(
        :title,
        :location_detail,
        :location_type,
        :location_longitude,
        :location_latitude,
        :location_zoom,
        :description,
        :time_zone,
        :external,
        :starts_at,
        :ends_at,
        network_ids: []).merge(creator: current_member)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_member!
  load_resource through: :current_community

  def calendar
    @events = current_network.events.
      on_date(date, current_member.time_zone).
      order(:starts_at)
  end

  def show
    @rsvp = @event.rsvps.find_by(member: current_member)
  end

  def rsvp
    @rsvp = @event.rsvps.find_or_initialize_by(member: current_member)
    if @rsvp.update_attributes(rsvp_params)
      redirect_to(
        [current_community, current_network, @event],
        notice: "You RSVP'd to the event as #{ @rsvp }.")
    else
      redirect_to(
        [current_community, current_network, @event],
        alert: "Error creating your RSVP : #{@rsvp.errors.first.second}")
    end
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:state).merge(network: current_network)
  end

  def date
    if params[:year].nil? || params[:month].nil? || params[:day].nil?
      redirect_to(
        [current_community, current_network, @event],
        alert: 'Invalid date.')
    else
      @date = Date.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}")
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  RSVP_STATES = {
    attending: 'Join',
    not_attending: 'Decline',
    maybe_attending: 'Maybe'
  }

  def rsvp_event_button(event, state)
    rsvp_link(event, state, RSVP_STATES[state.to_sym], class: 'btn btn-default')
  end

  def rsvp_link(event, state, name = nil, html_options = {})
    link_to(
      name,
      rsvp_community_network_event_path(current_community, current_network, event, rsvp: { state: state }),
      html_options.merge(method: :patch))
  end

  def event_static_map(event)
    query = {
      center: event.location_coordinates,
      size: '230x230',
      zoom: event.location_zoom,
      markers: "color:blue|#{ event.location_coordinates }"
    }
    url = URI.parse("https://maps.googleapis.com/maps/api/staticmap")
    url.query = query.to_query
    image_tag(url, class: 'img-responsive')
  end

  def event_header(event)
    starts_at_in_member_tz = event_start_time(event)
    safe_join([
      event.title,
      tag('br'),
      content_tag('small', starts_at_in_member_tz)], ' ')
  end

  def event_type_label(event, with_event: false)
    wording = []
    wording << (event.external? ? 'External' : 'Network')
    wording << 'Event' if with_event
    style = event.external? ? 'external-event' : 'community-event'
    content_tag('span', wording.join(' '), class: "label #{ style }")
  end

  def event_start_time(event, format = '%A, %B %d, %Y at %l:%M%P')
    event.starts_at.in_time_zone(current_member.time_zone).strftime(format)
  end

  def event_times(event, time_zone)
    template = '%A, %B %d, %Y at %l:%M%P'
    times = {}
    times['Begins'] = event.starts_at.in_time_zone(time_zone).strftime(template)
    times['Ends'] = event.ends_at.in_time_zone(time_zone).strftime(template)
    times['Timezone'] = time_zone
    times
  end

  def event_link(event)
    link_to event.title, [current_community, current_network, event]
  end
end

app/views/admin/events/_event.html.erb
<tr>
  <td><%= event_type_label(event) %></td>
  <td><%= event.networks.map(&:name).join(', ') %></td>
  <td><%= link_to event.title.truncate(30), [event.community, event.default_network, event] %></td>
  <td><%= event.starts_at.strftime('%A, %B %d, %Y at %l:%M%P') %></td>
  <td><%= event.ends_at.strftime('%A, %B %d, %Y at %l:%M%P') %></td>
  <td><%= event.time_zone.truncate(15) %></td>
  <td><%= event.location_detail.truncate(15) %></td>
  <td>
    <% if can? :update, event %>
      <%= link_to('Edit', edit_community_admin_event_path(current_community, event), class: 'btn btn-default btn-xs') %>
    <% end %>
  </td>
</tr>

app/views/admin/events/_form.html.erb
<%= simple_form_for([current_community, :admin, event], html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean }) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <%= panel 'General Info', columns: 5 do %>
      <%= f.input :title, autofocus: true %>
      <%= f.input :description, input_html: { rows: 7 }, hint: markdown_hint %>
      <%= f.input :external, collection: [[true, 'External Event'], [false, 'Internal Network Event']], label_method: :last, value_method: :first, as: :radio_buttons, item_wrapper_class: 'inline', label: 'Type' %>
      <%= f.association :networks,
                        input_html: { class: 'network_checkboxes' },
                        collection: current_community.networks,
                        as: :check_boxes %>
    <% end %>

    <%= panel 'Location and Time', columns: 7 do %>
      <%= f.input :location, required: true do %>
        <%= f.select :location_type, Event::LOCATION_TYPES.map { |k, v| [k.to_s.humanize, k, { 'data-detail-label': v }] }, {}, class: 'select required form-control' %>
      <% end %>
      <%= f.input :location_detail, label: 'Detail' %>
      <%= f.input :location_latitude, as: :hidden %>
      <%= f.input :location_longitude, as: :hidden %>
      <%= f.input :location_zoom, as: :hidden %>
      <div id="map_canvas"></div>
      <%= f.input :starts_at, label: 'Starts', as: :date_time_with_steps, wrapper_html: { class: 'datetime-inline' } %>
      <%= f.input :ends_at, label: 'Ends', as: :date_time_with_steps, wrapper_html: { class: 'datetime-inline' } %>
      <%= render partial: 'shared/forms/time_zone', locals: { form: f } %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="text-left">
        <%= f.button :submit, "Save Event" %>
      </div>
    </div>
    <div class="col-lg-6">
      <% if event.persisted? %>
        <div class="text-right small">
          <%= link_to('Delete this Event', community_admin_event_path(current_community, event), method: :delete, data: { confirm: "Are you sure you want to remove this Event?"}) %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<%= panel "Edit Event", columns: 12 do %>
  <%= render partial: 'form', locals: { event: @event } %>
<% end %>

app/views/admin/events/index.html.erb
<%
  title 'Events'
  page_header 'Events' do
    safe_join([
      "Filter by: ",
      network_filter_dropdown(resource: 'Event'),
      link_to('Create new Event', new_community_admin_event_path(current_community), class: 'btn btn-success')
    ], ' ')
  end
%>

<div class="row">
  <div class="col-sm-12" role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active" role="presentation">
        <a aria-controls="upcoming-events" data-toggle="tab" href="#upcoming-events" role="tab">
          Upcoming Events
          <span class="label label-info"><%= @upcoming_events.total_count %></span>
        </a>
      </li>
      <% if @past_events.any? %>
        <li role="presentation">
          <a aria-controls="past-events" data-toggle="tab" href="#past-events" role="tab">
            Past Events
            <span class="label label-info"><%= @past_events.size %></span>
          </a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active fade in" id="upcoming-events" role="tabpanel">
        <table class="table table-striped">
          <thead>
            <th></th>
            <th class="dropdown"><%= network_filter_dropdown(resource: 'Event', html_class: 'btn-xs') %></th>
            <th>Title</th>
            <th>Starts at</th>
            <th>Ends at</th>
            <th>Time Zone</th>
            <th>Location</th>
            <th></th>
          </thead>
          <tbody>
            <%= render collection: @upcoming_events, partial: 'event' %>
          </tbody>
        </table>
        <div class="text-center">
          <%= paginate @upcoming_events %>
        </div>
      </div>
      <div class="tab-pane fade" id="past-events" role="tabpanel">
        <table class="table table-striped">
          <thead>
            <th></th>
            <th>Title</th>
            <th>Starts at</th>
            <th>Ends at</th>
            <th>Time Zone</th>
            <th>Location</th>
            <th></th>
          </thead>
          <tbody>
            <%= render collection: @past_events, partial: 'event' %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/new.html.erb
<%= panel "New Event", columns: 12 do %>
  <%= render partial: 'form', locals: { event: @event } %>
<% end %>