config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :member, lambda { |u| u.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :communities, path: '', except: :index do
    get 'admin/dashboard'

    namespace :admin do
      resource :community, only: [:edit, :update]
      resources :networks
      resources :events, except: [:show]
      resources :companies
      resources :members do
        patch 'resend_invitation', on: :member
      end
      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end

    resources :networks, path: '', only: :show do
      namespace :admin do
        resources :events, except: [:show]
        resources :companies
        resources :members do
          patch 'resend_invitation', on: :member
        end
      end

      resource :calendar, only: :show do
        get 'feeds/:auth_token/:type',
          to: 'calendar_feeds#subscribe',
          as: 'feeds',
          constraints: { type: /events|availabilities/ }
        get 'feeds/:auth_token/reservations',
          to: 'calendar_feeds#reservations',
          as: 'reservation_feeds'
      end

      get 'availabilities/:year/:month/:day',
          to: 'availabilities#calendar',
          as: 'availability_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      get 'events/:year/:month/:day',
          to: 'events#calendar',
          as: 'event_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      resources :messages, only: :index do
        get 'search', on: :collection
      end

      resources :members, only: [:index, :show] do
        member do
          patch :follow
          delete :unfollow
        end

        resources :activities, only: :index
        resource :calendar, only: :show
        resources :messages
        resources :discussions, only: :index

        get 'availabilities/:year/:month/:day',
            to: 'availabilities#slots',
            as: 'availability_slots',
            constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

        resources :availabilities, except: [:show] do
          resource :slots,
                   path: 'slots/:hour/:minute',
                   constraints: { hour: /\d{1,2}/, minute: /\d{1,2}/ } do
                     collection do
                       post :reserve, to: 'slots#create'
                       delete :release, to: 'slots#destroy'
                     end
                   end
        end
      end

      get 'discussions/tagged/:tag_id',
          to: 'discussions#index',
          as: 'discussion_tag'

      resources :discussions do
        resources :comments, only: [:create, :update, :destroy]
        member do
          patch :follow
          delete :unfollow
        end
      end

      resources :events, only: [:show] do
        member do
          patch :rsvp
        end
      end

      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end
  end

  scope ':community_id' do
    devise_for(
      :members,
      skip: [:registrations],
      controllers: {
        invitations: 'invitations',
        sessions: 'sessions'
      })
    as :member do
      delete '/leave', to: 'registrations#destroy', as: 'destroy_member_registration'
    end
    scope ':network_id' do
      as :member do
        scope 'account' do
          # settings & cancellation
          get '/', to: 'registrations#edit', as: 'edit_member_registration'
          put '/', to: 'registrations#update'
        end
      end
    end
  end

  root 'welcome#index'
  get 's3_callback/:model', to: 'uploads#s3_callback', as: "s3_callback"
  get '*missing' => redirect('/')
end

app/models/network.rb
class Network < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :community

  validates :name, :slug, presence: true, uniqueness: { scope: :community }

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships
  has_many :activities
  has_many :discussions, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :discussion_tags
  has_and_belongs_to_many :companies
  has_and_belongs_to_many :events
  has_and_belongs_to_many :availabilities

  scope :ordered, -> { order(name: :desc) }

  def last_in_community?
    community.networks.size == 1
  end

  def availabilities_for_show
    Rails.cache.fetch(cache_key_for_availabilities) do
      availabilities.
        joins(:member).
        by_daterange(Date.today, 1.week.from_now.to_date).
        ordered
    end
  end

  def activities_for_show
    Rails.cache.fetch(cache_key_for_activities) do
      activities.includes(:owner).ordered.limit(20)
    end
  end

  private

  def base_cache_key
    "/networks/#{id}/#{updated_at.to_i}"
  end

  [:availabilities, :activities].each do |relation|
    define_method "cache_key_for_#{ relation }" do
      "#{base_cache_key}/#{relation}"
    end
  end
end

app/controllers/admin/networks_controller.rb
module Admin
  class NetworksController < AdminController
    load_and_authorize_resource through: :current_community, find_by: :slug

    def index
      @networks = current_community.networks
      @networks = @networks.ordered.page params[:page]
    end

    def new
      render 'admin/networks/form'
    end

    def create
      if @network.save
        redirect_to_admin_networks_path('Network was successfully created.')
      else
        render 'admin/networks/form', alert: 'Error creating network.'
      end
    end

    def edit
      render 'admin/networks/form'
    end

    def update
      @network.update(network_params)
      if @network.save
        redirect_to_admin_networks_path('Network was successfully updated.')
      else
        render 'networks/form', alert: 'Error updating network.'
      end
    end

    def destroy
      @network.destroy
      redirect_to_admin_networks_path('Network was successfully deleted.')
    end

    private

    def network_params
      params.require(:network).permit(:name)
    end

    def redirect_to_admin_networks_path(notice)
      redirect_to(
        community_admin_networks_path(current_community),
        notice: notice)
    end
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  # layout :false
  before_action :authorize_through_magic_connect!
  before_action :set_current_network
  before_action :set_activities

  include FilterConcern

  def show
    authorize! :read, current_network
    @events = current_network.events.upcoming.ordered
    @availabilities = current_network.availabilities_for_show
  end

  protected

  def default_filter
    :public
  end

  def community
    @current_network.community
  end

  def set_activities
    @activities = begin
      if filter == :personal
        activities = @current_network.activities
        activities.for(current_member).includes(:owner).ordered.limit(20)
      else
        @current_network.activities_for_show
      end
    end
  end

  def set_current_network
    @current_network ||= Network.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to member.default_network
  end
end

app/views/admin/networks/_network.html.erb
<tr>
  <td><%= network.name %></td>
  <td>
    <% if can? :update, network %>
      <%= link_to('Edit', edit_community_admin_network_path(current_community, network), class: 'btn btn-default btn-xs') %>
    <% end %>
  </td>
</tr>

app/views/admin/networks/form.html.erb
<%
  title 'Networks'
  page_header @network.new_record? ? "New Network" : "Edit #{ @network.name }"
%>

<div class='row'>
  <%= simple_form_for([current_community, :admin, @network], html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean }) do |f| %>
    <div class='col-lg-6'>
      <%= f.input :name, autofocus: true, placeholder: 'Name' %>
      <% if @network.persisted? && can?(:destroy, @network) %>
        <div class="text-right">
          <%= link_to('Remove this network', community_admin_network_path(current_community, @network), method: :delete, data: { confirm: "Are you sure you want to remove this Network?"}, class: 'btn btn-xs btn-hover btn-hover-danger') %>
        </div>
      <% end %>
    </div>
    <div class='text-left col-lg-3'>
      <%= f.button :submit, f.object.new_record? ? "Save" : "Update" %>
    </div>
  <% end %>
</div>

app/views/admin/networks/index.html.erb
<%
  title 'Networks'
  page_header 'Networks' do
    link_to 'New Network', new_community_admin_network_path(current_community), class: 'btn btn-success'
  end
%>
<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped">
      <thead>
        <th>Name</th>
        <th></th>
      </thead>
      <tbody>
        <%= render @networks %>
      </tbody>
    </table>
    <div class="text-center">
      <%= paginate @networks %>
    </div>
  </div>
</div>