config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :member, lambda { |u| u.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :communities, path: '', except: :index do
    get 'admin/dashboard'

    namespace :admin do
      resource :community, only: [:edit, :update]
      resources :networks
      resources :events, except: [:show]
      resources :companies
      resources :members do
        patch 'resend_invitation', on: :member
      end
      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end

    resources :networks, path: '', only: :show do
      namespace :admin do
        resources :events, except: [:show]
        resources :companies
        resources :members do
          patch 'resend_invitation', on: :member
        end
      end

      resource :calendar, only: :show do
        get 'feeds/:auth_token/:type',
          to: 'calendar_feeds#subscribe',
          as: 'feeds',
          constraints: { type: /events|availabilities/ }
        get 'feeds/:auth_token/reservations',
          to: 'calendar_feeds#reservations',
          as: 'reservation_feeds'
      end

      get 'availabilities/:year/:month/:day',
          to: 'availabilities#calendar',
          as: 'availability_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      get 'events/:year/:month/:day',
          to: 'events#calendar',
          as: 'event_calendar',
          constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

      resources :messages, only: :index do
        get 'search', on: :collection
      end

      resources :members, only: [:index, :show] do
        member do
          patch :follow
          delete :unfollow
        end

        resources :activities, only: :index
        resource :calendar, only: :show
        resources :messages
        resources :discussions, only: :index

        get 'availabilities/:year/:month/:day',
            to: 'availabilities#slots',
            as: 'availability_slots',
            constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

        resources :availabilities, except: [:show] do
          resource :slots,
                   path: 'slots/:hour/:minute',
                   constraints: { hour: /\d{1,2}/, minute: /\d{1,2}/ } do
                     collection do
                       post :reserve, to: 'slots#create'
                       delete :release, to: 'slots#destroy'
                     end
                   end
        end
      end

      get 'discussions/tagged/:tag_id',
          to: 'discussions#index',
          as: 'discussion_tag'

      resources :discussions do
        resources :comments, only: [:create, :update, :destroy]
        member do
          patch :follow
          delete :unfollow
        end
      end

      resources :events, only: [:show] do
        member do
          patch :rsvp
        end
      end

      resources :companies, only: [:index, :show, :edit, :update] do
        resources :members, only: [:new, :create, :edit, :update]
      end
    end
  end

  scope ':community_id' do
    devise_for(
      :members,
      skip: [:registrations],
      controllers: {
        invitations: 'invitations',
        sessions: 'sessions'
      })
    as :member do
      delete '/leave', to: 'registrations#destroy', as: 'destroy_member_registration'
    end
    scope ':network_id' do
      as :member do
        scope 'account' do
          # settings & cancellation
          get '/', to: 'registrations#edit', as: 'edit_member_registration'
          put '/', to: 'registrations#update'
        end
      end
    end
  end

  root 'welcome#index'
  get 's3_callback/:model', to: 'uploads#s3_callback', as: "s3_callback"
  get '*missing' => redirect('/')
end

app/views/shared/_activity.html.erb
<tr>
  <td>
    <% if activity.owner.networks.include?(current_network)  %>
      <%= member_link activity.owner %>
    <% else %>
      <%= image_tag(activity.owner.avatar.url(:icon), class: 'img-rounded') %>
      <%= activity.owner.full_name %>
    <% end %>
    <%= yield %>
    <small class='text-muted'><%= time_tag activity.updated_at %></small>
  </td>
</tr>

app/views/shared/_flash.html.erb
<% if notice && notice.length > 0 %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">&times</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if warning && warning.length > 0 %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">&times</span>
    </button>
    <%= warning %>
  </div>
<% end %>
<% if alert && alert.length > 0 %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">&times</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_follow_button.html.erb
<%- if object.followers.include? current_member %>
  <%= link_to(
        'Unfollow',
        send("unfollow_community_network_#{ object.class.to_s.downcase }_path",
             current_community,
             current_network,
             object),
        class: 'btn btn-default',
        method: :delete) if can?(:unfollow, object) %>
<% else %>
  <%= link_to(
        'Follow',
        send("follow_community_network_#{ object.class.to_s.downcase }_path",
             current_community,
             current_network,
             object),
        class: 'btn btn-default',
        method: :patch) if can?(:follow, object) %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-2">
        <%= image_tag('logobw.png', class: 'img-responsive footer__logo') %>
      </div>
      <div class="col-lg-2">
        <ul class='nav footer__nav'>
          <li><%= link_to 'About', 'http://mymagic.my/about' %></li>
          <li><%= link_to 'Community', 'http://mymagic.my/community' %></li>
          <li><%= link_to 'Programs', 'http://mymagic.my/programs' %></li>
          <li><%= link_to 'Events', 'http://mymagic.my/events' %></li>
        </ul>
      </div>
      <div class="col-lg-2">
        <ul class='nav footer__nav'>
          <li><%= link_to 'Newsletter', 'http://mymagic.my/newsletter' %> </li>
          <li><%= link_to 'News', 'http://mymagic.my/news' %> </li>
          <li><%= link_to 'Jobs', 'http://mymagic.my/jobs' %> </li>
          <li><%= link_to 'Contact', 'http://mymagic.my/contact' %> </li>
        </ul>
      </div>
      <div class="col-lg-6 text-right">
        <address>
          Malaysian Global Innovation & Creativity Centre,<br>
          Block 3730 APEC, 63000 Cyberjaya, Malaysia.<br>
          Tel: +60 3 8324 4800<br>
          Email: <%= mail_to 'enquiries@mymagic.my' %>
        </address>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-lg-3 footer__social-media-services">
        <%= link_to image_tag('social_media_services/facebook.png'), 'https://www.facebook.com/magic.cyberjaya', target: '_blank' %>
        <%= link_to image_tag('social_media_services/twitter.png'), 'https://twitter.com/magiccyberjaya', target: '_blank' %>
        <%= link_to image_tag('social_media_services/instagram.png'), 'https://instagram.com/magic_cyberjaya', target: '_blank' %>
        <%= link_to image_tag('social_media_services/youtube.png'), 'https://www.youtube.com/channel/UCIT_ihmWh5f3MCobvEwWMaA', target: '_blank' %>
      </div>
      <div class="col-lg-3 col-lg-push-6 text-right">
        <%= link_to('Privacy Policy', 'http://mymagic.my/privacy-policy', target: '_blank') %> | Initiated by M.O.F.
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-magic navbar-static-top navbar-standard">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_network.present? %>
        <div class="navbar-brand-dropdown dropdown navbar-brand">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="community-brand"><%= current_network.name %></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% current_member.networks.each do |network| %>
              <li><%= link_to network.name, [network.community, network] %></li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <div class="navbar-brand">
          <span class="community-brand">
            <strong>MaGIC</strong> Communities
          </span>
        </div>
      <% end %>
    </div>
    <% if member_signed_in? %>
      <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
          <% if current_network %>
            <%= nav_link "Activities", [current_community, current_network] %>
            <%= nav_link "Discussions", [current_community, current_network, Discussion] if can? :read, Discussion %>
            <%= nav_link "Members", [current_community, current_network, Member] if can? :read, Member %>
            <%= nav_link "Companies", [current_community, current_network, Company] if can? :read, Company %>
            <%= nav_link "Events", community_network_calendar_path(current_community, current_network) if can? :read, :calendar %>
            <%= nav_link 'Setup Office Hours', new_community_network_member_availability_path(current_community, current_network, current_member) if can? :create, Availability %>
          <% else %>
            <%= nav_link "Welcome", root_path %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown member">
            <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
              <% cache(["unread_messages_count", @current_member]) do %>
                <%= content_tag('span', unread_messages.size, class: 'badge unread-messages') if unread_messages.present? %>
              <% end %>
              <%= image_tag(current_member.avatar.url(:icon), class: 'navbar-avatar img-rounded') %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% if current_member.companies.any? %>
                <% current_member.companies.each do |company| %>
                  <%= nav_link company.name, [current_community, current_network, company] %>
                <% end %>
                <li class="divider"></li>
              <% end %>
              <%= nav_link "Administration", edit_community_admin_community_path(current_community) if can? :administrate, current_community %>
              <%= nav_link "#{ current_member.full_name }'s Profile", [current_community, current_network, current_member] %>
              <%= nav_link "Change Password", "http://connect.mymagic.my/profile", target: '_blank' %>
              <%= nav_link "Preferences", edit_member_registration_path(current_community, current_network) %>
              <% if can? :read, Message %>
                <% cache(["messages_navigation", @current_member]) do %>
                  <%= nav_link [current_community, current_network, current_member.last_chat_participant, Message] do %>
                      Messages
                      <%= content_tag('span', unread_messages.size, class: 'badge unread-messages') if unread_messages.present? %>
                  <% end %>
                <% end %>
              <% end %>
              <%= nav_link "Sign out", destroy_member_session_path(current_community), method: :delete %>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <% if current_community %>
            <%= nav_link "Log in", new_member_session_path(current_community) %>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_paginated_collection.html.erb
<div id="paginated_collection__content">
  <% if objects.any? %>
    <div class="<%= class_name.underscore %>-group">
      <%= render objects %>
      <% %w(lg md sm xs).each do |size| %>
        <div class="clearfix visible-<%= size %>-block"></div>
      <% end %>
    </div>
    <div class="row text-center">
      <%= paginate objects, remote: true %>
    </div>
    <div class="row text-center text-muted small filter-description">
      <%= send(class_name.underscore + '_filter_description') %>
    </div>
  <% else %>
    <h3 class="text-center">
      No <%= class_name.pluralize %> found.
    </h3>
  <% end %>
</div>

app/views/shared/_social_media_link.html.erb
<% if social_media_link.as_icon? %>
  <%= link_to(social_media_icon(social_media_link.service), social_media_link.url, target: '_blank', class: 'social-media-link__icon') %>
<% else %>
  <%= link_to(social_media_link.service, social_media_link.url, target: '_blank', class: 'btn btn-default btn-sm social-media-link__btn') %>
<% end %>